### ISSUE TITLE
Build fails with: ../bin/fble-disassemble.c:36:3: error: ‘__builtin_fputs’ argument missing terminating nul

### ISSUE THREAD

**Issue by thinkingcow** [ruhler/fable#1]
System: Up to date Debian Raspbian Bullseye on Raspberry PI/4
Build complete removing -Werror from build.ninja
Gcc output:

[55/742] gcc -MMD -MF bin/fble-disassemble.o.d -std=c99 -pedantic -Wall -Wextra -Wshadow -Werror -gdwarf-3 -ggdb -O3 -I ../include -I ./bin -c -o bin/fble-disassemble.o ../bin/fble-disassemble.c
FAILED: bin/fble-disassemble.o 
gcc -MMD -MF bin/fble-disassemble.o.d -std=c99 -pedantic -Wall -Wextra -Wshadow -Werror -gdwarf-3 -ggdb -O3 -I ../include -I ./bin -c -o bin/fble-disassemble.o ../bin/fble-disassemble.c
../bin/fble-disassemble.c: In function ‘main’:
../bin/fble-disassemble.c:36:3: error: ‘__builtin_fputs’ argument missing terminating nul [-Werror=stringop-overflow=]
   36 |   fprintf(stream, "%s", fbldUsageHelpText);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../bin/fble-disassemble.c:15:
./bin/fble-disassemble.usage.h:1:21: note: referenced argument declared here
    1 | const unsigned char fbldUsageHelpText[] = {
      |                     ^~~~~~~~~~~~~~~~~
../bin/fble-disassemble.c:36:3: error: ‘__builtin_fputs’ argument missing terminating nul [-Werror=stringop-overflow=]
   36 |   fprintf(stream, "%s", fbldUsageHelpText);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../bin/fble-disassemble.c:15:
./bin/fble-disassemble.usage.h:1:21: note: referenced argument declared here
    1 | const unsigned char fbldUsageHelpText[] = {
      |                     ^~~~~~~~~~~~~~~~~
../bin/fble-disassemble.c:36:3: error: ‘__builtin_fputs’ argument missing terminating nul [-Werror=stringop-overflow=]
   36 |   fprintf(stream, "%s", fbldUsageHelpText);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../bin/fble-disassemble.c:15:
./bin/fble-disassemble.usage.h:1:21: note: referenced argument declared here
    1 | const unsigned char fbldUsageHelpText[] = {
      |                     ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[56/742] gcc -MMD -MF bin/fble-deps.o.d -std=c99 -pedantic -Wall -Wextra -Wshadow -Werror -gdwarf-3 -ggdb -O3 -I ../include -I ./bin -c -o bin/fble-deps.o ../bin/fble-deps.c
FAILED: bin/fble-deps.o 
gcc -MMD -MF bin/fble-deps.o.d -std=c99 -pedantic -Wall -Wextra -Wshadow -Werror -gdwarf-3 -ggdb -O3 -I ../include -I ./bin -c -o bin/fble-deps.o ../bin/fble-deps.c
../bin/fble-deps.c: In function ‘main’:
../bin/fble-deps.c:51:3: error: ‘__builtin_fputs’ argument missing terminating nul [-Werror=stringop-overflow=]
   51 |   fprintf(stream, "%s", fbldUsageHelpText);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../bin/fble-deps.c:15:
./bin/fble-deps.usage.h:1:21: note: referenced argument declared here
    1 | const unsigned char fbldUsageHelpText[] = {
      |                     ^~~~~~~~~~~~~~~~~
../bin/fble-deps.c:51:3: error: ‘__builtin_fputs’ argument missing terminating nul [-Werror=stringop-overflow=]
   51 |   fprintf(stream, "%s", fbldUsageHelpText);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../bin/fble-deps.c:15:
./bin/fble-deps.usage.h:1:21: note: referenced argument declared here
    1 | const unsigned char fbldUsageHelpText[] = {
      |                     ^~~~~~~~~~~~~~~~~
../bin/fble-deps.c:51:3: error: ‘__builtin_fputs’ argument missing terminating nul [-Werror=stringop-overflow=]
   51 |   fprintf(stream, "%s", fbldUsageHelpText);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../bin/fble-deps.c:15:
./bin/fble-deps.usage.h:1:21: note: referenced argument declared here
    1 | const unsigned char fbldUsageHelpText[] = {
      |                     ^~~~~~~~~~~~~~~~~
../bin/fble-deps.c:51:3: error: ‘__builtin_fputs’ argument missing terminating nul [-Werror=stringop-overflow=]
   51 |   fprintf(stream, "%s", fbldUsageHelpText);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../bin/fble-deps.c:15:
./bin/fble-deps.usage.h:1:21: note: referenced argument declared here
    1 | const unsigned char fbldUsageHelpText[] = {
      |                     ^~~~~~~~~~~~~~~~~

**Comment by ruhler** [comment]
https://github.com/ruhler/fable/commit/e24165449d6275acd6e589f6242d1ce91af16c11
